name: CI/CD Docker Staging & Production

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      promote_to_production:
        description: 'Promote to production'
        required: true
        default: 'false'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image for staging
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/simple-landing-page:latest .

      - name: Push image to staging
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/simple-landing-page:latest

      - name: Promote to production
        if: github.event.inputs.promote_to_production == 'true'
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/simple-landing-page:latest ${{ secrets.DOCKERHUB_USERNAME }}/simple-landing-page:production
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/simple-landing-page:production

          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/simple-landing-page:latest ${{ secrets.DOCKERHUB_USERNAME }}/simple-landing-page:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/simple-landing-page:latest
